### PR TITLE
feat(theme): add real time theme manager

### PR DESCRIPTION
**Pull request by matiasjgoitea**
Fix: #8

### CODE REVIEW

**Comment by matiasjgoitea** [comment]
Fix: #9

**Comment by matiasjgoitea** [comment]
I used ThemeProvider from Styled Components

**Comment by EricTurf** [comment]
@matiasjgoitea I am happy that you used `ThemeProvider` :) seems like you have conflicting files so if that can be resolved I will merge this

**Comment by matiasjgoitea** [comment]
Sorry, i didn't notice. It's done :D

**Pull request merged**
