### PR TITLE
Add notes feature

### PR DESCRIPTION
**Pull request by AceGentile**
adding a note button into lower toolbar to select values to use as notes and display them into game board

ref. issue #14

### CODE REVIEW

**Comment by EricTurf** [comment]
@AceGentile 

Thank you for your contribution, reviewing it now :)

**Comment by EricTurf** [comment]
@AceGentile 

Looks awesome, the only problem I noticed is that if you select every number as a note, past 6 numbers it will overflow the container. I was wondering if you could make it wrap at a certain length of purposely format it to be like
```
1 3 5 7 9
2 4 6 8
```

here is a screenshot 

sudoku-notes

**Comment by AceGentile** [comment]
Hi Erik,

thanx for your quick review!
I fixed that ugly overflow issue and rebased, let me know if it works

**Comment by EricTurf** [comment]
@AceGentile 
Love it, thank you so much for this!

**Pull request merged**
