### PR TITLE
[#12] Add eslint and fix lint errors

### PR DESCRIPTION
**Pull request by ra100**
Sorry, I might have overdo this a bit, by adding airbnb eslint rules, feel free to reject, if it's too much

### CODE REVIEW

**Comment by ra100** [comment]
need to fix eslint version conflict with create-react-app

**Comment by ra100** [comment]
@EricTurf sure, it's possible. Just need to find the correct rule

**Comment by ra100** [comment]
should be better now

**Comment by EricTurf** [comment]
@ra100 Thank you :)

**Pull request merged**
