### PR TITLE
Added home screen #38

### PR DESCRIPTION
**Pull request by kartikpandey2**
- added home Screen 
- replaced select in difficulty Component with antd Select component

### CODE REVIEW

**Comment by kartikpandey2** [comment]
@EricTurf resolved Conflicts

**Comment by EricTurf** [comment]
@kartikpandey2 
some issues I noticed, I cannot compile the app since `_events` is not imported from `sudoku.jsx`
and in `app.jsx` the need for the `react-router` is completly useless. See https://github.com/EricTurf/react-sudoku/blob/d7a57c255e68f3b6f93ea917c561d6c27ea9f1ec/src/app.jsx

You can just add your code from `app.jsx` to this :)

**Comment by kartikpandey2** [comment]
@EricTurf  done check now 😄

**Comment by EricTurf** [comment]
@kartikpandey2 thank you good work :)

**Pull request merged**
